#!/bin/bash

# create error message if arguments weren't passed ini
# expects -s sitename

usage() { echo "Usage: $0 [-s <string>]" 1>&2; exit 1; }

# read arguments
while getopts ":s:" option; do
    case "${option}" in
        s)
            s=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${s}" ]; then
    usage
fi

# Set up variables
SITENAME=${s}
PASSWORD=`pwgen -1 7`

# Create user, create database and grant privileges
mysql -uroot -e "CREATE USER ${SITENAME}@'localhost' IDENTIFIED BY '${PASSWORD}';"
mysql -uroot -e "CREATE DATABASE ${SITENAME};"
mysql -uroot -e "GRANT ALL PRIVILEGES ON ${SITENAME}.* TO ${SITENAME}@'localhost' IDENTIFIED BY '${PASSWORD}';"

# Output the generated password
echo ${PASSWORD}
